[build]
command = "pnpm run netlify"
publish = "dist/eskil-portfolio/browser"

[context.production]
command = ""
publish = "dist/eskil-portfolio/browser"

[[redirects]]
from = "/*"
to = "/404/index.html"
status = 404
